// Mock data for Inventory Dashboard
// Based on seed_data.sql — remove this file when backend API is ready

export const MOCK_CATEGORIES = [
  {
    id: 1,
    name: 'Dairy',
    parent_group: 'food',
    display_order: 1,
    items: [
      {
        id: 1,
        name: 'Cottage Cheese',
        total_quantity: 0,
        low_stock_threshold: 20,
        status: 'out_of_stock',
      },
      {
        id: 2,
        name: 'Eggs',
        total_quantity: 176,
        low_stock_threshold: 20,
        status: 'normal',
      },
      {
        id: 3,
        name: 'Milk',
        total_quantity: 15,
        low_stock_threshold: 50,
        status: 'low_stock',
      },
      {
        id: 16,
        name: 'Bacon',
        total_quantity: 0,
        low_stock_threshold: 20,
        status: 'out_of_stock',
      },
    ],
  },
  {
    id: 2,
    name: 'Canned Fruits and Vegetables',
    parent_group: 'food',
    display_order: 2,
    items: [
      {
        id: 4,
        name: 'Canned Corn',
        total_quantity: 100,
        low_stock_threshold: 30,
        status: 'normal',
      },
      {
        id: 5,
        name: 'Black Beans',
        total_quantity: 45,
        low_stock_threshold: 30,
        status: 'normal',
      },
      {
        id: 6,
        name: 'Canned Broccoli',
        total_quantity: 0,
        low_stock_threshold: 20,
        status: 'out_of_stock',
      },
      {
        id: 15,
        name: 'Bananas',
        total_quantity: 0,
        low_stock_threshold: 30,
        status: 'out_of_stock',
      },
    ],
  },
  {
    id: 3,
    name: 'Canned Meat',
    parent_group: 'food',
    display_order: 3,
    items: [
      {
        id: 7,
        name: 'Canned Beef',
        total_quantity: 0,
        low_stock_threshold: 20,
        status: 'out_of_stock',
      },
      {
        id: 14,
        name: 'Beef Jerky',
        total_quantity: 0,
        low_stock_threshold: 15,
        status: 'out_of_stock',
      },
    ],
  },
  {
    id: 4,
    name: 'Pasta',
    parent_group: 'food',
    display_order: 4,
    items: [
      {
        id: 8,
        name: 'Angel Hair Pasta',
        total_quantity: 67,
        low_stock_threshold: 30,
        status: 'normal',
      },
      {
        id: 9,
        name: 'Penne Pasta',
        total_quantity: 23,
        low_stock_threshold: 30,
        status: 'low_stock',
      },
      {
        id: 12,
        name: 'Alfredo Sauce',
        total_quantity: 42,
        low_stock_threshold: 20,
        status: 'normal',
      },
    ],
  },
  {
    id: 5,
    name: 'Soup',
    parent_group: 'food',
    display_order: 5,
    items: [
      {
        id: 10,
        name: 'Chicken Noodle Soup',
        total_quantity: 623,
        low_stock_threshold: 50,
        status: 'normal',
      },
      {
        id: 11,
        name: 'Tomato Soup',
        total_quantity: 163,
        low_stock_threshold: 50,
        status: 'normal',
      },
    ],
  },
  {
    id: 6,
    name: 'Cooking Oil',
    parent_group: 'food',
    display_order: 6,
    items: [],
  },
  {
    id: 7,
    name: 'Tree Nuts',
    parent_group: 'food',
    display_order: 7,
    items: [],
  },
  {
    id: 8,
    name: 'Shellfish',
    parent_group: 'food',
    display_order: 8,
    items: [],
  },
  {
    id: 9,
    name: 'Cleaning Supplies',
    parent_group: 'non_food',
    display_order: 1,
    items: [
      {
        id: 13,
        name: 'Kleenex Tissue Boxes',
        total_quantity: 35,
        low_stock_threshold: 10,
        status: 'normal',
      },
    ],
  },
  {
    id: 10,
    name: 'Household Goods',
    parent_group: 'non_food',
    display_order: 2,
    items: [],
  },
];

// Mock item detail data (batches by item_id)
// Used by ItemDetailModal when clicking an item
export const MOCK_ITEM_DETAILS = {
  1: {
    id: 1,
    name: 'Cottage Cheese',
    category: { id: 1, name: 'Dairy' },
    total_quantity: 0,
    low_stock_threshold: 20,
    batches: [{ id: 1, expiration_date: '2026-03-01', quantity: 0 }],
  },
  2: {
    id: 2,
    name: 'Eggs',
    category: { id: 1, name: 'Dairy' },
    total_quantity: 176,
    low_stock_threshold: 20,
    batches: [
      { id: 2, expiration_date: '2026-01-01', quantity: 22 },
      { id: 3, expiration_date: '2026-02-01', quantity: 22 },
      { id: 4, expiration_date: '2026-03-01', quantity: 22 },
      { id: 5, expiration_date: '2026-04-01', quantity: 0 },
      { id: 6, expiration_date: '2026-05-01', quantity: 0 },
      { id: 7, expiration_date: '2026-06-01', quantity: 22 },
      { id: 8, expiration_date: '2026-07-01', quantity: 22 },
      { id: 9, expiration_date: '2026-08-01', quantity: 22 },
      { id: 10, expiration_date: '2026-09-01', quantity: 22 },
      { id: 11, expiration_date: '2026-10-01', quantity: 22 },
      { id: 12, expiration_date: '2026-11-01', quantity: 22 },
      { id: 13, expiration_date: '2026-12-01', quantity: 0 },
    ],
  },
  3: {
    id: 3,
    name: 'Milk',
    category: { id: 1, name: 'Dairy' },
    total_quantity: 15,
    low_stock_threshold: 50,
    batches: [{ id: 14, expiration_date: '2026-06-01', quantity: 15 }],
  },
  4: {
    id: 4,
    name: 'Canned Corn',
    category: { id: 2, name: 'Canned Fruits and Vegetables' },
    total_quantity: 100,
    low_stock_threshold: 30,
    batches: [{ id: 15, expiration_date: '2027-01-01', quantity: 100 }],
  },
  5: {
    id: 5,
    name: 'Black Beans',
    category: { id: 2, name: 'Canned Fruits and Vegetables' },
    total_quantity: 45,
    low_stock_threshold: 30,
    batches: [{ id: 16, expiration_date: '2027-08-01', quantity: 45 }],
  },
  6: {
    id: 6,
    name: 'Canned Broccoli',
    category: { id: 2, name: 'Canned Fruits and Vegetables' },
    total_quantity: 0,
    low_stock_threshold: 20,
    batches: [],
  },
  7: {
    id: 7,
    name: 'Canned Beef',
    category: { id: 3, name: 'Canned Meat' },
    total_quantity: 0,
    low_stock_threshold: 20,
    batches: [],
  },
  8: {
    id: 8,
    name: 'Angel Hair Pasta',
    category: { id: 4, name: 'Pasta' },
    total_quantity: 67,
    low_stock_threshold: 30,
    batches: [{ id: 22, expiration_date: '2027-04-01', quantity: 67 }],
  },
  9: {
    id: 9,
    name: 'Penne Pasta',
    category: { id: 4, name: 'Pasta' },
    total_quantity: 23,
    low_stock_threshold: 30,
    batches: [{ id: 21, expiration_date: '2027-03-01', quantity: 23 }],
  },
  10: {
    id: 10,
    name: 'Chicken Noodle Soup',
    category: { id: 5, name: 'Soup' },
    total_quantity: 623,
    low_stock_threshold: 50,
    batches: [
      { id: 17, expiration_date: '2027-05-01', quantity: 234 },
      { id: 18, expiration_date: '2027-12-01', quantity: 389 },
    ],
  },
  11: {
    id: 11,
    name: 'Tomato Soup',
    category: { id: 5, name: 'Soup' },
    total_quantity: 163,
    low_stock_threshold: 50,
    batches: [
      { id: 19, expiration_date: '2026-03-01', quantity: 43 },
      { id: 20, expiration_date: '2027-06-01', quantity: 120 },
    ],
  },
  12: {
    id: 12,
    name: 'Alfredo Sauce',
    category: { id: 4, name: 'Pasta' },
    total_quantity: 42,
    low_stock_threshold: 20,
    batches: [{ id: 23, expiration_date: '2027-05-01', quantity: 42 }],
  },
  13: {
    id: 13,
    name: 'Kleenex Tissue Boxes',
    category: { id: 9, name: 'Cleaning Supplies' },
    total_quantity: 35,
    low_stock_threshold: 10,
    batches: [{ id: 24, expiration_date: null, quantity: 35 }],
  },
  14: {
    id: 14,
    name: 'Beef Jerky',
    category: { id: 3, name: 'Canned Meat' },
    total_quantity: 0,
    low_stock_threshold: 15,
    batches: [],
  },
  15: {
    id: 15,
    name: 'Bananas',
    category: { id: 2, name: 'Canned Fruits and Vegetables' },
    total_quantity: 0,
    low_stock_threshold: 30,
    batches: [],
  },
  16: {
    id: 16,
    name: 'Bacon',
    category: { id: 1, name: 'Dairy' },
    total_quantity: 0,
    low_stock_threshold: 20,
    batches: [],
  },
};
